apiVersion: v1
kind: Service
metadata:
  name: order-project-service
  namespace: dn
spec:
  type: ClusterIP
  selector:
    app: order-service-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
      #nodePort: 30082